require "rails/generators"
require "tty-spinner"

module AiRspecWriter
  class InstallGenerator < Rails::Generators::Base
    source_root File.expand_path("templates", __dir__)

    def install_ai_rspec_writer
      puts "\n🚀 Starting `ai_rspec_writer` setup...\n".yellow
      check_rspec_installed
      configure_spec_helper
      configure_rails_helper
      puts "\n✅ `ai_rspec_writer` setup completed successfully!\n".green
    end

    private

    # Check if RSpec is installed, otherwise install it
    def check_rspec_installed
      spinner = TTY::Spinner.new("🔍 Checking if RSpec is installed... :spinner")
      spinner.auto_spin

      if File.exist?("spec/rails_helper.rb") && File.exist?("spec/spec_helper.rb")
        spinner.success("✅ RSpec is already installed.")
      else
        spinner.stop("⚠️ RSpec not found. Installing...".red)
        generate "rspec:install"
        puts "✅ RSpec installed successfully.".green
      end
    end

    # Append content to spec_helper.rb
    def configure_spec_helper
      spec_helper_path = "spec/spec_helper.rb"
      spinner = TTY::Spinner.new("🔧 Configuring `spec_helper.rb`... :spinner")
      spinner.auto_spin

      if File.exist?(spec_helper_path)
        original_content = File.read(spec_helper_path)
        new_content = "#{spec_file_content}\n\n" + original_content
        File.write(spec_helper_path, new_content)
        spinner.success("✅ Updated `spec_helper.rb` with AI RSpec settings.")
      else
        spinner.error("⚠️ `spec_helper.rb` not found. Skipping...".red)
      end
    end

    # Append content to rails_helper.rb after `RSpec.configure do |config|`
    def configure_rails_helper
      rails_helper_path = "spec/rails_helper.rb"
      target_line = "RSpec.configure do |config|"
      spinner = TTY::Spinner.new("🔧 Configuring `rails_helper.rb`... :spinner")
      spinner.auto_spin

      if File.exist?(rails_helper_path)
        content = File.readlines(rails_helper_path)
        index = content.find_index { |line| line.strip == target_line.strip }

        if index
          content.insert(index + 1, "#{rails_helper_content}\n")
          File.write(rails_helper_path, content.join)
          spinner.success("✅ Successfully inserted configurations into `rails_helper.rb`.")
        else
          spinner.error("⚠️ `RSpec.configure` block not found in `rails_helper.rb`. Skipping...".red)
        end
      else
        spinner.error("⚠️ `rails_helper.rb` not found. Skipping...".red)
      end
    end

    # Content for spec_helper.rb
    def spec_file_content
      <<~RUBY
        # Auto-generated by ai_rspec_writer
        require 'simplecov'
        SimpleCov.start 'rails' do
          add_filter '/spec/'
          add_filter '/config/'
          add_filter '/vendor/'
          add_filter '/db/'
          add_filter '/bin/'
        end
        # Auto-generated by ai_rspec_writer
      RUBY
    end

    # Content for rails_helper.rb with proper indentation
    def rails_helper_content
      <<~RUBY.indent(2)
        # Auto-generated by ai_rspec_writer
        config.include FactoryBot::Syntax::Methods

        # Include Shoulda Matchers
        Shoulda::Matchers.configure do |shoulda_config|
          shoulda_config.integrate do |with|
            with.test_framework :rspec
            with.library :rails
          end
        end
        # Auto-generated by ai_rspec_writer
      RUBY
    end
  end
end
